Remove unnecessary defines for Hexagon reference kernel build. (#2091)
These were preventing reference kernels from being built with `TARGET=hexagon`. See http://b/281821666#comment5 for additional context.

Manually tested that the following command passes with this change:
```
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=hexagon -j8 test
```

And without this change we get the following error:
```
tensorflow/lite/micro/kernels/fully_connected.cc:74:49: error: no member named 'filter_buffer_index' in 'tflite::OpDataFullyConnected'
                                         &data->filter_buffer_index);
                                          ~~~~  ^
tensorflow/lite/micro/kernels/fully_connected.cc:129:55: error: no member named 'filter_buffer_index' in 'tflite::OpDataFullyConnected'
              context->GetScratchBuffer(context, data.filter_buffer_index));
                                                 ~~~~ ^
```

Note that we do not have any CI coverage for reference kernels with Hexagon since the expectation is that everyone should use the optimized kernels.

However, we still provide a best-effort attempt to explicitly use the reference kernels, if needed.

BUG=http://b/281821666